apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: mar21-codegen-cibuild-model-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mar21-codegen-cibuild-model-server
    app.kubernetes.io/part-of: mar21-codegen-cibuild
  name: mar21-codegen-cibuild-model-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: mar21-codegen-cibuild-model-server
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: mar21-codegen-cibuild-model-server
    spec:
      initContainers:
        - name: model-file
          image: quay.io/rh-ee-jdubrick/mistral-7b-code-16k-qlora:testingci
          command: ['/usr/bin/install', '/model/model.file', '/shared/']
          volumeMounts:
            - name: model-file
              mountPath: /shared
      containers:
        - env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "8001"
            - name: MODEL_PATH
              value: /model/model.file
            - name: CHAT_FORMAT
              value: openchat
          image: quay.io/ai-lab/llamacpp_python:latest
          volumeMounts:
            - name: model-file
              mountPath: /model
          name: app-model-service
          ports:
            - containerPort: 8001
          securityContext:
            runAsNonRoot: true
      volumes:
        - name: model-file
          emptyDir: {}
